In [617]:
import numpy as np

In [618]:
threshold = 0.5

def f_1(s):
    return 1 / (1 + np.e ** (-s))


def fd_1(s):
    return s * (1 - s)

def f_activation(x):
    return np.where(x > threshold, 1, 0)

# Pojedynczy neuron

In [619]:
x = np.array([[-1, 1, 2],
              [-1, 2, 3],
              [-1, 2, 1],
              [-1, 3, 1]])

y = np.array([[1, 1, 0, 0]]).T

w = np.array([[1., 1., 1.]])

n = 0.1

In [620]:
s = x @ w.T
print('s')
s

s


array([[2.],
       [4.],
       [2.],
       [3.]])

In [621]:
print('f(s)')
f_val = f_1(s)
f_val

f(s)


array([[0.88079708],
       [0.98201379],
       [0.88079708],
       [0.95257413]])

In [622]:
fd_val = fd_1(s)
print("f'(s)")
fd_val

f'(s)


array([[ -2.],
       [-12.],
       [ -2.],
       [ -6.]])

In [623]:
y_minus_f = y - f_val
print('t - y')
y_minus_f

t - y


array([[ 0.11920292],
       [ 0.01798621],
       [-0.88079708],
       [-0.95257413]])

In [624]:
print("(t-y) * f'(s)")
y_minus_f_times_fd_val = y_minus_f * fd_val
y_minus_f_times_fd_val

(t-y) * f'(s)


array([[-0.23840584],
       [-0.21583452],
       [ 1.76159416],
       [ 5.71544476]])

In [625]:
print("(t-y) * f'(s) * x")
delta_without_learning = y_minus_f_times_fd_val * x
delta_without_learning

(t-y) * f'(s) * x


array([[ 0.23840584, -0.23840584, -0.47681169],
       [ 0.21583452, -0.43166904, -0.64750356],
       [-1.76159416,  3.52318831,  1.76159416],
       [-5.71544476, 17.14633428,  5.71544476]])

In [626]:
print("delta w without lr")
delta_without_learning_mean = delta_without_learning.mean(axis=0)
delta_without_learning_mean.reshape((1,len(delta_without_learning_mean)))

delta w without lr


array([[-1.75569964,  4.99986193,  1.58818092]])

In [627]:
print("delta w mean")
delta_w = n * delta_without_learning_mean.reshape((1,len(delta_without_learning_mean)))
delta_w

delta w mean


array([[-0.17556996,  0.49998619,  0.15881809]])

In [628]:
print('new w')
w += delta_w
w

new w


array([[0.82443004, 1.49998619, 1.15881809]])

In [629]:
print('classification')
test_sample = np.array([[-1, 4, 1]])

print(w @ test_sample.T)
ttt = f_activation(test_sample @ w.T)
ttt

classification
[[6.33433283]]


array([[1]])

# Siec neuronowa

In [630]:
lr = 0.5

x1 = 0.05
x2 = 0.1

b1 = 0.35
b2 = 0.6

t1 = 0.01
t2 = 0.99

w1 = 0.15
w2 = 0.2
w3 = 0.25
w4 = 0.3
w5 = 0.4
w6 = 0.45
w7 = 0.5
w8 = 0.55



In [631]:
print('H1')
H1 = x1 * w1 + x2 * w2 + b1
H1

H1


0.3775

In [632]:
print('out H1')
outH1 = f_1(H1)
outH1

out H1


0.5932699921071872

In [633]:
print('H2')
H2 = x1 * w3 + x2 * w4 + b1
H2

H2


0.39249999999999996

In [634]:
print('out H2')
outH2 = f_1(H2)
outH2

out H2


0.596884378259767

In [635]:
print('y1')
y1 = outH1 * w5 + outH2 * w6 + b2
y1

y1


1.10590596705977

In [636]:
print('out y1')
outy1 = f_1(y1)
outy1

out y1


0.7513650695523157

In [637]:
print('y2')
y2 = outH1 * w7 + outH2 * w8 + b2
y2

y2


1.2249214040964653

In [638]:
print('out y2')
outy2 = f_1(y2)
outy2

out y2


0.7729284653214625

### Total error

In [639]:
L = (((t1 - outy1) ** 2)) + (((t2 - outy2) ** 2))
L

0.5967422175200054

In [640]:
Ly1 = (((t1 - outy1) ** 2))
Ly1

0.54962216635231

In [641]:
Ly2 = (((t2 - outy2) ** 2))
Ly2

0.04712005116769549

### Output layer back propagation

In [642]:
grad_y1_t1 = -(t1 - outy1) * outy1 * (1 - outy1)

In [643]:
deltaw5 = lr * grad_y1_t1 * outH1
deltaw5

0.041083520282115385

In [644]:
new_w5 = w5 - deltaw5
new_w5

0.35891647971788465

In [645]:
deltaw6 = lr * grad_y1_t1 * outH2
deltaw6

0.04133381392376662

In [646]:
new_w6 = w6 - deltaw6
new_w6

0.4086661860762334

In [647]:
grad_y2_t2 = -(t2 - outy2) * outy2 * (1 - outy2)

In [648]:
deltaw7 = lr * grad_y2_t2 * outH1
deltaw7

-0.011301270238737535

In [649]:
new_w7 = w7 - deltaw7
new_w7

0.5113012702387375

In [650]:
deltaw8 = lr * grad_y2_t2 * outH2
deltaw8

-0.011370121107989111

In [651]:
new_w8 = w8 - deltaw8
new_w8

0.5613701211079891

### Hidden layer back propagation

In [652]:
print('new w1')
deltaw1 = ((grad_y1_t1 * w5) + (grad_y2_t2 * w7)) * outH1 * (1 - outH1) * x1
new_w1 = w1 - (lr * deltaw1)
new_w1

new w1


0.1497807161327628

In [653]:
print('new w2')
deltaw2 = ((grad_y1_t1 * w5) + (grad_y2_t2 * w7)) * outH1 * (1 - outH1) * x2
new_w2 = w2 - lr * deltaw2
new_w2

new w2


0.19956143226552567

In [654]:
print('new w3')
deltaw3 = ((grad_y1_t1 * w6) + (grad_y2_t2 * w8)) * outH2 * (1 - outH2) * x1
new_w3 = w3 - lr * deltaw3
new_w3

new w3


0.24975114363236958

In [655]:
print('new w4')
deltaw4 = ((grad_y1_t1 * w6) + (grad_y2_t2 * w8)) * outH2 * (1 - outH2) * x2
new_w4 = w4 - lr * deltaw4
new_w4

new w4


0.29950228726473915