In [86]:
import math
import numpy as np
import scipy.linalg
from scipy.linalg import pinv, inv


def l1(x: np.array, y: np.array):
    if x.shape != y.shape:
        raise Exception('Shapes dont match')

    s = 0

    for i in range(len(x)):
        s += abs(y[i] - x[i])
    return s


def l2(x: np.array, y: np.array):
    if x.shape != y.shape:
        raise Exception('Shapes dont match')

    s = 0

    for i in range(len(x)):
        s += (y[i] - x[i]) ** 2
    return s ** (1 / 2)


def linf(x: np.array, y: np.array):
    if x.shape != y.shape:
        raise Exception('Shapes dont match')

    k = x.shape[0]
    s = 0

    for i in range(k):
        s += abs(y[i] - x[i]) ** k
    return s ** (1 / k)


def mean_vector(x):
    """
    na wejsciu podwany jest stojacy wektor np [[1], [1]] a nie [1, 1]
    :param x:
    :return:
    """
    n = x.shape[0]
    mean = np.zeros((1, x.shape[1]))

    for i in range(n):
        mean += x[i]

    mean /= n
    return mean


def covariation_matrix(x: np.array):
    """
    przyjmuje punkt x jako stojacy np. [[1], [2]] a nie [[1, 2]]
    :param x:
    :return:
    """
    n = x.shape[0]
    print(n)

    mean = mean_vector(x)

    print("srednia mi")
    print(mean)

    summer = np.zeros((x.shape[1], x.shape[1]))

    for i in range(n):
        xx = x[i] - mean
        summer += xx.T @ xx

    summer /= n

    print('macierz kowariancji:')
    print(summer.round(3))

    for i in range(summer.shape[0]):
        for j in range(summer.shape[1]):
            if i != j:
                print("pearson dla ", i + 1, j + 1, ": ", (summer[i][j] / ((summer[i][i] ** (1 / 2)) * (summer[j][j] ** (1 / 2)))))
                print("zaokraglenie: ", round(summer[i][j] / ((summer[i][i] ** (1 / 2)) * (summer[j][j] ** (1 / 2))), 3))

    return summer



def mahalanobis_distance(x: np.array, c: np.array, mi: np.array):
    """
    przyjmuje punkt x jako lezacy np. [1, 2] a nie [[1], [2]]
    """
    cinv = inv(c)
    xx = x - mi

    return xx @ cinv @ xx.T


def mahalanobis_1d(x_1d, mi_1d, var):
    std = var ** (1/2)

    return abs(x_1d - mi_1d) / std


def fisher_wspolczynnik(mi1, mi2, c1, c2):
    for i in range(len(mi1)):
        std1 = c1[i][i] ** (1/2)
        std2 = c2[i][i] ** (1/2)
        print("fished dla ", i, ": ", (abs(mi1[i] - mi2[i]) / (std1 + std2)))
        print("zaokraglenie ", round((abs(mi1[i] - mi2[i]) / (std1 + std2)), 3))




In [87]:
a = np.array([[0, 0]]).T
b = np.array([[1, 1]]).T
c = np.array([[0, 0.7]]).T

print(l1(a, c))
print(l1(b, c))

print(l2(a, c))
print(l2(b, c))

print(linf(a, c))
print(linf(b, c))

[0.7]
[1.3]
[0.7]
[1.04403065]
[0.7]
[1.04403065]


In [88]:
a = np.array([[-2, -2], [-1, 1], [1, -1], [2, 2]])
c = covariation_matrix(a)
c

4
srednia mi
[[0. 0.]]
macierz kowariancji:
[[2.5 1.5]
 [1.5 2.5]]
pearson dla  1 2 :  0.5999999999999999
zaokraglenie:  0.6
pearson dla  2 1 :  0.5999999999999999
zaokraglenie:  0.6


array([[2.5, 1.5],
       [1.5, 2.5]])

In [89]:
miX = mean_vector(a)

dd = np.array([4, -4])

ddd = np.array([4, 4])

mahalanobis_distance(dd, c, miX)

array([[32.]])

In [90]:
mahalanobis_distance(ddd, c, miX)

array([[8.]])

In [91]:
prupki = np.array([[2, 4, 6, 4], [1, 0, 1, 2]])
print(prupki)

miP = mean_vector(prupki.T)

maciesz = covariation_matrix(prupki.T)

[[2 4 6 4]
 [1 0 1 2]]
4
srednia mi
[[4. 1.]]
macierz kowariancji:
[[2.  0. ]
 [0.  0.5]]
pearson dla  1 2 :  0.0
zaokraglenie:  0.0
pearson dla  2 1 :  0.0
zaokraglenie:  0.0


In [92]:
inv_maciesz = pinv(maciesz)

In [93]:
punkt = np.array([[4, 4]])
mahalanobis_distance(punkt, maciesz, miP)

# l2(punkt.T, miP.T)

array([[18.]])

In [94]:
mahalanobis_1d(0, 1.5, 1.25)

1.3416407864998738

In [95]:
w1 = np.array([1.5, 1.5]).T
w2 = np.array([-2, -2]).T

cw1 = np.array([[1.25, -1], [-1, 1.25]])
cw2 = np.array([[3, 1], [1, 1]])

fisher_wspolczynnik(w1, w2, cw1, cw2)

fished dla  0 :  1.2280336376379648
zaokraglenie  1.228
fished dla  1 :  1.6524758424985277
zaokraglenie  1.652
